### ISSUE TITLE
MAINTAINER WANTED

### ISSUE THREAD

**Issue by k3a** [mattv8/yourls-ldap-plugin#32]
As I've moved away from using YOURLS, I'm finding it challenging to keep up with the maintenance of the plugin (see a stale #28 and #31).

If there's someone with prior experience in maintaining GitHub projects and a good grasp of PHP, I'm actively seeking an individual
who can take over the responsibilities of maintaining and continuing the development of this project.

If you fit these criteria, I'd greatly appreciate it if you could express your interest in this issue.

Thanks!

**Comment by mattv8** [comment]
Hey if you'd like, I can maintain it. I think I'm the most recent PR too, although I realize it's been a few years.

**Comment by k3a** [comment]
Hey. Thank you for saving the repo! In order to transfer the ownership I need you to rename or remove your fork (github says: mattv8/yourls-ldap-plugin already exists)

**Comment by jorrit** [comment]
Why not make an organization for Yourls? Might me useful in the future.

**Comment by mattv8** [comment]
Alright I went ahead and closed the PR, there shouldn't be any conflicts now.

**Comment by k3a** [comment]
The PR was not the problem but the existence of the repo in your account is. :)
Maybe it would be enough to rename it or you may need to make a local clone of your fork into your PC first and delete it in the GitHub.

<img width="723" alt="Screenshot 2024-04-24 at 21 12 22" src="https://github.com/k3a/yourls-ldap-plugin/assets/966992/28a9d9aa-fea5-432e-ac60-0526becbf55b">

**Comment by mattv8** [comment]
🤦 My bad, you're absolutely right. I've deleted my local mattv8/yourls-ldap-plugin, give it another go.

**Comment by k3a** [comment]
The transfer has been initiated and it is waiting for something, maybe your confirmation or their cron job to pick it up. We'll see...

**Comment by mattv8** [comment]
I'm awaiting a notification-- nothing has come through yet.

**Comment by k3a** [comment]
Thanks for volunteering! It shouldn't need too much maintenance but it needed someone who is using YOURLS actively like you so you can test the changes and sort out eventual backward incompatibilities. Closing the issue then.
